# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PerfectSelf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PerfectSelf
  pod 'AWSS3'
  pod 'JJFloatingActionButton'
  pod 'FSCalendar'
  pod 'BDatePicker', :path => '../BDatePicker-master/'
  pod 'DropDown'

end
