# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PerfectSelf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PerfectSelf
  pod 'AWSS3'
  pod 'JJFloatingActionButton'
  pod 'FSCalendar'
  pod 'DropDown'
  pod 'HSPopupMenu'
  pod 'RangeSeekSlider'
  pod 'IQKeyboardManagerSwift'
  pod "Koyomi"
  pod 'AnimatedCardInput'
  pod "SwiftGifOrigin"
  pod 'GoogleAPIClientForREST/Calendar'
  pod 'GoogleSignIn', '~> 5.0.2'
  pod 'Stripe'
end